import "./globals.css";
import { Nunito_Sans } from "next/font/google";
import NavTop from "@/components/NavTop/NavTop";
import Nav from '@/components/Navbar/NavCenter/Navbar'
import MobileNav from '@/components/Mobile/MobileNav/MobileNav'
const nunito = Nunito_Sans({ subsets: ["latin"], weight:  ['400', '500','600','700', '800'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="hu">
      <body className={nunito.className}>
        <NavTop />
        <Nav/>
        <MobileNav />
        {children}
      </body>
    </html>
  );
}
